using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Practice_Project.Migrations
{
    /// <inheritdoc />
    public partial class MakeRollNumberAtuoIncrement : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
        ALTER TABLE ""Students"" 
        ALTER COLUMN ""RollNumber"" TYPE integer USING ""RollNumber""::integer;

        ALTER TABLE ""Students"" 
        ALTER COLUMN ""RollNumber"" SET NOT NULL;

        ALTER TABLE ""Students"" 
        ALTER COLUMN ""RollNumber"" ADD GENERATED BY DEFAULT AS IDENTITY;
    ");
        }
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "RollNumber",
                table: "Students",
                type: "character varying(30)",
                maxLength: 30,
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer")
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
        }
    }
}
